server:
  port: 8081
## master 数据源配置
master:
  datasource:
    url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

## slave 数据源配置
slave:
  datasource:
    url: jdbc:mysql://localhost:3306/slave?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

#热部署
spring:
  devtools:
    restart:
      enabled: true